debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false # default
  sql.init.mode: always  # data.sql rule[NEVER, ALWAYS, EMBEDDED]
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client_id: ${KAKAO_APP_KEY}
            client_secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect_uri: "{baseUrl}/login/oauth2/code/kakao"
            client_authentication_method: POST
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user_info_uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id


---

#spring:
#  config.activate.on-profile: testdb
#    datasource:
#      url: jdbc:h2:mem:board;mode=mysql
#      driverClassName: org.h2.Driver
#    sql.init.mode: always
#    test.database.replace: none

---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always # test data 넣어줌 (data.sql)

---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb